#MongoDB configuration
spring.data.mongodb.uri = mongodb://localhost:27017/tunifyapp

# Cloudinary configuration
cloudinary.cloud-name=doeafwufm
cloudinary.api-key=288338966958237
cloudinary.api-secret=cCTxBQqWH_I2uBgXIv0J5v6DaJM

# File upload configuration
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# JWT information
jwt.secret=Y3BzYWY5M2pzODJmcWwxMnNqM2tmcTkwcWxzM2tzOWhubWFza2Zh==
# # 24 Stunden (1 Tag) jwt token ist aktive
jwt.expiration=86400000


## Cloudinary configuration
#cloudinary.cloud-name=#${CLOUDINARY_NAME}
#cloudinary.api-key=${CLOUDINARY_API_KEY}
#cloudinary.api-secret=${CLOUDINARY_SECRET_KEY}